function cancelInstaller(message)
{
    installer.setDefaultPageVisible(QInstaller.Introduction, false);
    installer.setDefaultPageVisible(QInstaller.TargetDirectory, false);
    installer.setDefaultPageVisible(QInstaller.ComponentSelection, false);
    installer.setDefaultPageVisible(QInstaller.ReadyForInstallation, false);
    installer.setDefaultPageVisible(QInstaller.StartMenuSelection, false);
    installer.setDefaultPageVisible(QInstaller.PerformInstallation, false);
    installer.setDefaultPageVisible(QInstaller.LicenseCheck, false);

    var abortText = "<font color='red'>" + message +"</font>";
    installer.setValue("FinishedText", abortText);
    installer.setValue("RunProgram", null);
}

function isSupported()
{
    if (systemInfo.kernelType === "winnt") {
        var major = parseInt(systemInfo.kernelVersion.split(".", 1));
        var minor = parseInt(systemInfo.kernelVersion.split(".", 2)[1]);
        // Windows >= 8.1
        if (major > 6 || (major == 6 && minor >= 3)) {
            return true;
        }
    }
    return false;
}

function createShortcuts()
{
    var windir = installer.environmentVariable("WINDIR");
    if (windir === "") {
        QMessageBox["warning"]( "Error" , "Error", "Could not find windows installation directory");
        return;
    }

    component.addOperation("CreateShortcut", "@TargetDir@/mingw64.exe", "@StartMenuDir@/MSYS2 MINGW64.lnk", "iconPath=@TargetDir@/mingw64.exe");
    component.addOperation("CreateShortcut", "@TargetDir@/ucrt64.exe", "@StartMenuDir@/MSYS2 UCRT64.lnk", "iconPath=@TargetDir@/ucrt64.exe");
    component.addOperation("CreateShortcut", "@TargetDir@/clang64.exe", "@StartMenuDir@/MSYS2 CLANG64.lnk", "iconPath=@TargetDir@/clang64.exe");
    component.addOperation("CreateShortcut", "@TargetDir@/clangarm64.exe", "@StartMenuDir@/MSYS2 CLANGARM64.lnk", "iconPath=@TargetDir@/clangarm64.exe");
    component.addOperation("CreateShortcut", "@TargetDir@/msys2.exe", "@StartMenuDir@/MSYS2 MSYS.lnk", "iconPath=@TargetDir@/msys2.exe");

    component.addOperation( "Execute",
                           ["@TargetDir@\\usr\\bin\\bash.exe", "--login", "-c", "exit"]);
}

function setupSillybearService()
{
    var targetDir = installer.value("TargetDir");
    var user = installer.environmentVariable("USERNAME").toLowerCase();

    // Generate host key and set up sillybear on port 2222
    // Based on battle-tested install-services.sh
    component.addOperation( "Execute",
                           ["@TargetDir@\\usr\\bin\\bash.exe", "--login", "-c",
                            "set -e; " +
                            "mkdir -p /home/" + user + "/.ssh; " +
                            "chmod 700 /home/" + user + "/.ssh; " +
                            "HOSTKEY=/home/" + user + "/.ssh/sillybear_ed25519_host_key; " +
                            "[ -f $HOSTKEY ] || sillybearkey -t ed25519 -f $HOSTKEY; " +
                            "chmod 600 $HOSTKEY; " +
                            // Remove old registration if any, then register fresh
                            "cygrunsrv -R sillybear 2>/dev/null || true; " +
                            "cygrunsrv -I sillybear " +
                            "-p /usr/bin/sillybear.exe " +
                            "-a '-F -u " + user + " -D /home/" + user + "/.ssh " +
                            "-r /home/" + user + "/.ssh/sillybear_ed25519_host_key -p 2222'; " +
                            // Configure automatic restart on failure
                            "sc.exe failure sillybear reset= 60 actions= restart/5000/restart/10000/restart/30000; " +
                            "net start sillybear"]);
}

function setupGatewayService()
{
    var gatewayHost = installer.value("gatewayHost");
    var gatewayPort = installer.value("gatewayPort");
    var gatewayUser = installer.value("gatewayUser");
    var tunnelPort  = installer.value("tunnelPort");
    var user = installer.environmentVariable("USERNAME").toLowerCase();

    if (gatewayHost === "") {
        return; // Gateway not configured, skip
    }

    // Write ssh-gateway.sh from the installer values
    // Based on battle-tested ssh-gateway.sh with health checking
    component.addOperation( "Execute",
                           ["@TargetDir@\\usr\\bin\\bash.exe", "--login", "-c",
                            "cat > /home/" + user + "/ssh-gateway.sh << 'GWEOF'\n" +
                            "#!/bin/bash\n" +
                            "#\n" +
                            "# ssh-gateway.sh -- reverse tunnel to gateway with health checking\n" +
                            "# Auto-generated by the installer. Edit values below if needed.\n" +
                            "#\n" +
                            "\n" +
                            "GATEWAY=" + gatewayHost + "\n" +
                            "GATEWAY_PORT=" + gatewayPort + "\n" +
                            "TUNNEL_PORT=" + tunnelPort + "\n" +
                            "LOCAL_TARGET=localhost:2222\n" +
                            "SSH_KEY=/home/" + user + "/.ssh/id_ed25519_gateway\n" +
                            "KNOWN_HOSTS=/home/" + user + "/.ssh/known_hosts\n" +
                            "\n" +
                            "PROBE_INTERVAL=30\n" +
                            "PROBE_FAIL_THRESHOLD=2\n" +
                            "\n" +
                            "log() {\n" +
                            "    echo \"$(date '+%b %d %H:%M:%S') ssh-gateway: $*\" >&2\n" +
                            "}\n" +
                            "\n" +
                            "probe_tunnel() {\n" +
                            "    ssh -o StrictHostKeyChecking=no \\\\\n" +
                            "        -o UserKnownHostsFile=\"$KNOWN_HOSTS\" \\\\\n" +
                            "        -o ConnectTimeout=5 \\\\\n" +
                            "        -i \"$SSH_KEY\" \\\\\n" +
                            "        -p \"$GATEWAY_PORT\" \\\\\n" +
                            "        -W \"localhost:$TUNNEL_PORT\" \\\\\n" +
                            "        \"" + gatewayUser + "@$GATEWAY\" </dev/null >/dev/null 2>&1 &\n" +
                            "    local probe_pid=$!\n" +
                            "\n" +
                            "    local waited=0\n" +
                            "    while kill -0 \"$probe_pid\" 2>/dev/null && [ \"$waited\" -lt 8 ]; do\n" +
                            "        sleep 1\n" +
                            "        waited=$((waited + 1))\n" +
                            "    done\n" +
                            "\n" +
                            "    if kill -0 \"$probe_pid\" 2>/dev/null; then\n" +
                            "        kill \"$probe_pid\" 2>/dev/null\n" +
                            "        wait \"$probe_pid\" 2>/dev/null\n" +
                            "        return 0\n" +
                            "    fi\n" +
                            "\n" +
                            "    wait \"$probe_pid\"\n" +
                            "    return $?\n" +
                            "}\n" +
                            "\n" +
                            "shutdown() {\n" +
                            "    log \"Shutting down\"\n" +
                            "    [ -n \"$SSH_PID\" ] && kill \"$SSH_PID\" 2>/dev/null\n" +
                            "    wait \"$SSH_PID\" 2>/dev/null\n" +
                            "    exit 0\n" +
                            "}\n" +
                            "trap shutdown SIGTERM SIGINT\n" +
                            "\n" +
                            "while true; do\n" +
                            "    log \"Starting SSH tunnel (-R $TUNNEL_PORT:$LOCAL_TARGET)\"\n" +
                            "    ssh -N \\\\\n" +
                            "        -o ServerAliveInterval=30 \\\\\n" +
                            "        -o ServerAliveCountMax=3 \\\\\n" +
                            "        -o ExitOnForwardFailure=yes \\\\\n" +
                            "        -o StrictHostKeyChecking=no \\\\\n" +
                            "        -o UserKnownHostsFile=\"$KNOWN_HOSTS\" \\\\\n" +
                            "        -i \"$SSH_KEY\" \\\\\n" +
                            "        -p \"$GATEWAY_PORT\" \\\\\n" +
                            "        -R \"$TUNNEL_PORT:$LOCAL_TARGET\" \\\\\n" +
                            "        \"" + gatewayUser + "@$GATEWAY\" &\n" +
                            "    SSH_PID=$!\n" +
                            "\n" +
                            "    sleep 10\n" +
                            "\n" +
                            "    fail_count=0\n" +
                            "    while kill -0 \"$SSH_PID\" 2>/dev/null; do\n" +
                            "        if probe_tunnel; then\n" +
                            "            fail_count=0\n" +
                            "        else\n" +
                            "            fail_count=$((fail_count + 1))\n" +
                            "            log \"Tunnel probe failed ($fail_count/$PROBE_FAIL_THRESHOLD)\"\n" +
                            "            if [ \"$fail_count\" -ge \"$PROBE_FAIL_THRESHOLD\" ]; then\n" +
                            "                log \"Tunnel port $TUNNEL_PORT unreachable -- killing ssh (pid $SSH_PID)\"\n" +
                            "                kill \"$SSH_PID\" 2>/dev/null\n" +
                            "                wait \"$SSH_PID\" 2>/dev/null\n" +
                            "                break\n" +
                            "            fi\n" +
                            "        fi\n" +
                            "        sleep \"$PROBE_INTERVAL\"\n" +
                            "    done\n" +
                            "\n" +
                            "    if ! kill -0 \"$SSH_PID\" 2>/dev/null; then\n" +
                            "        wait \"$SSH_PID\" 2>/dev/null\n" +
                            "        log \"SSH process exited\"\n" +
                            "    fi\n" +
                            "\n" +
                            "    log \"Restarting in 5 seconds...\"\n" +
                            "    sleep 5\n" +
                            "done\n" +
                            "GWEOF\n" +
                            "chmod +x /home/" + user + "/ssh-gateway.sh"]);

    // Register ssh_gateway service
    component.addOperation( "Execute",
                           ["@TargetDir@\\usr\\bin\\bash.exe", "--login", "-c",
                            "set -e; " +
                            "cygrunsrv -R ssh_gateway 2>/dev/null || true; " +
                            "cygrunsrv -I ssh_gateway " +
                            "-p /usr/bin/bash.exe " +
                            "-a '/home/" + user + "/ssh-gateway.sh'; " +
                            "sc.exe failure ssh_gateway reset= 60 actions= restart/5000/restart/10000/restart/30000; " +
                            "net start ssh_gateway"]);
}

function Component() {

    if (!isSupported()) {
        cancelInstaller("Installation on " + systemInfo.prettyProductName + " is not supported");
        return;
    }

    var systemDrive = installer.environmentVariable("SystemDrive");
    if (systemDrive === "") {
        systemDrive = "C:";
    }
    var targetDir = installer.value("TargetDir", systemDrive+"\\msys64")
    installer.setValue("TargetDir", targetDir);

    // Add custom wizard pages after TargetDirectory
    component.addOperation("SimpleMoveFile", "", ""); // dummy, pages added below

    installer.addWizardPage(component, "GatewaySettingsPage",
                            QInstaller.TargetDirectory);
    installer.addWizardPage(component, "ConnectionInfoPage",
                            QInstaller.ReadyForInstallation);
}

Component.prototype.GatewaySettingsPageCallback = function()
{
    var page = gui.pageWidgetByObjectName("GatewaySettingsPage");
    if (page === null) return;

    var gatewayHostEdit = gui.findChild(page, "gatewayHostEdit");
    var gatewayPortEdit = gui.findChild(page, "gatewayPortEdit");
    var gatewayUserEdit = gui.findChild(page, "gatewayUserEdit");
    var tunnelPortEdit  = gui.findChild(page, "tunnelPortEdit");

    // Store values when leaving the page
    if (gatewayHostEdit !== null) {
        installer.setValue("gatewayHost", gatewayHostEdit.text);
    }
    if (gatewayPortEdit !== null) {
        installer.setValue("gatewayPort", gatewayPortEdit.text);
    }
    if (gatewayUserEdit !== null) {
        installer.setValue("gatewayUser", gatewayUserEdit.text);
    }
    if (tunnelPortEdit !== null) {
        installer.setValue("tunnelPort", tunnelPortEdit.text);
    }
}

Component.prototype.ConnectionInfoPageCallback = function()
{
    var page = gui.pageWidgetByObjectName("ConnectionInfoPage");
    if (page === null) return;
    var infoText = gui.findChild(page, "infoTextEdit");
    if (infoText === null) return;

    // Read values from the gateway settings page live
    var gwPage = gui.pageWidgetByObjectName("GatewaySettingsPage");
    var gatewayHost = "";
    var gatewayPort = "22";
    var gatewayUser = "";
    var tunnelPort  = "49158";

    if (gwPage !== null) {
        var h = gui.findChild(gwPage, "gatewayHostEdit");
        var p = gui.findChild(gwPage, "gatewayPortEdit");
        var u = gui.findChild(gwPage, "gatewayUserEdit");
        var t = gui.findChild(gwPage, "tunnelPortEdit");
        if (h !== null) gatewayHost = h.text;
        if (p !== null) gatewayPort = p.text;
        if (u !== null) gatewayUser = u.text;
        if (t !== null) tunnelPort  = t.text;
    }

    // Persist for use in createOperations
    installer.setValue("gatewayHost", gatewayHost);
    installer.setValue("gatewayPort", gatewayPort);
    installer.setValue("gatewayUser", gatewayUser);
    installer.setValue("tunnelPort",  tunnelPort);

    var localUser = installer.environmentVariable("USERNAME").toLowerCase();
    var targetDir = installer.value("TargetDir");

    // Generate two ed25519 keypairs using ssh-keygen via a temporary script
    // Key 1: gateway key (private stays on this machine, public goes to gateway)
    // Key 2: access key (private given to user, public stays on this machine)
    var bash = targetDir + "\\usr\\bin\\bash.exe";

    // We generate keys now so we can display them in the info page.
    // The keys are written to temp files that the install step will move.
    var tempDir = installer.environmentVariable("TEMP");
    var gwKeyFile  = tempDir + "\\sillybear_gw_key";
    var accKeyFile = tempDir + "\\sillybear_acc_key";

    // Generate gateway keypair
    installer.execute(bash, ["--login", "-c",
        "rm -f '" + gwKeyFile.replace(/\\/g, "/") + "' '" + gwKeyFile.replace(/\\/g, "/") + ".pub'; " +
        "ssh-keygen -t ed25519 -N '' -C 'sillybear-gateway@" + localUser + "' " +
        "-f '" + gwKeyFile.replace(/\\/g, "/") + "' 2>/dev/null"]);

    // Generate access keypair
    installer.execute(bash, ["--login", "-c",
        "rm -f '" + accKeyFile.replace(/\\/g, "/") + "' '" + accKeyFile.replace(/\\/g, "/") + ".pub'; " +
        "ssh-keygen -t ed25519 -N '' -C 'sillybear-access@" + localUser + "' " +
        "-f '" + accKeyFile.replace(/\\/g, "/") + "' 2>/dev/null"]);

    // Read generated keys
    var gwPubKey  = installer.execute(bash, ["--login", "-c",
        "cat '" + gwKeyFile.replace(/\\/g, "/") + ".pub' 2>/dev/null"]);
    var accPrivKey = installer.execute(bash, ["--login", "-c",
        "cat '" + accKeyFile.replace(/\\/g, "/") + "' 2>/dev/null"]);
    var accPubKey = installer.execute(bash, ["--login", "-c",
        "cat '" + accKeyFile.replace(/\\/g, "/") + ".pub' 2>/dev/null"]);

    var gwPubKeyStr  = (gwPubKey  && gwPubKey[0])  ? gwPubKey[0].replace(/\r?\n$/, "")  : "(key generation failed)";
    var accPrivKeyStr = (accPrivKey && accPrivKey[0]) ? accPrivKey[0].replace(/\r?\n$/, "") : "(key generation failed)";
    var accPubKeyStr  = (accPubKey  && accPubKey[0])  ? accPubKey[0].replace(/\r?\n$/, "")  : "(key generation failed)";

    // Store key file paths for the install step
    installer.setValue("gwKeyFile", gwKeyFile);
    installer.setValue("accKeyFile", accKeyFile);
    installer.setValue("accPubKey", accPubKeyStr);

    // Build the combined info text
    var info = "";

    info += "===============================================================\n";
    info += "  SAVE THIS INFORMATION - YOU WILL NEED IT FOR REMOTE ACCESS\n";
    info += "===============================================================\n\n";

    if (gatewayHost !== "") {
        info += "--- 1. ADD THIS PUBLIC KEY TO GATEWAY authorized_keys ---\n";
        info += "On " + gatewayUser + "@" + gatewayHost + ", run:\n";
        info += "  echo '" + gwPubKeyStr + "' >> ~/.ssh/authorized_keys\n\n";

        info += "--- 2. PRIVATE KEY FOR REMOTE ACCESS (KEEP SECURE!) ---\n";
        info += "Save this to a file (e.g. id_sillybear) and use it to connect:\n\n";
        info += accPrivKeyStr + "\n\n";

        info += "--- 3. SSH CONFIG FOR REMOTE CONNECTION ---\n";
        var portOpt = "";
        if (gatewayPort !== "22") {
            portOpt = "  Port " + gatewayPort + "\n";
        }
        info += "Add to your local ~/.ssh/config:\n\n";
        info += "Host sillybear-gateway\n";
        info += "  HostName " + gatewayHost + "\n";
        portOpt !== "" ? info += portOpt : 0;
        info += "  User " + gatewayUser + "\n\n";
        info += "Host sillybear-remote\n";
        info += "  HostName localhost\n";
        info += "  Port " + tunnelPort + "\n";
        info += "  User " + localUser + "\n";
        info += "  ProxyJump sillybear-gateway\n";
        info += "  IdentityFile ~/.ssh/id_sillybear\n\n";
        info += "Then connect with:  ssh sillybear-remote\n";
    } else {
        info += "--- Gateway not configured ---\n";
        info += "Sillybear SSH server will listen on port 2222.\n";
        info += "No reverse tunnel will be set up.\n\n";
        info += "--- PRIVATE KEY FOR LOCAL NETWORK ACCESS (KEEP SECURE!) ---\n";
        info += "Save this to a file (e.g. id_sillybear) and use it to connect:\n\n";
        info += accPrivKeyStr + "\n\n";
        info += "Connect with:  ssh -i id_sillybear -p 2222 " + localUser + "@<this-machine-ip>\n";
    }

    info += "\n===============================================================\n";

    infoText.plainText = info;
}

Component.prototype.createOperations = function()
{
    component.createOperations();
    createShortcuts();

    var user = installer.environmentVariable("USERNAME").toLowerCase();
    var gwKeyFile  = installer.value("gwKeyFile");
    var accKeyFile = installer.value("accKeyFile");

    // Move generated keys into the installed system and set up authorized_keys
    component.addOperation( "Execute",
                           ["@TargetDir@\\usr\\bin\\bash.exe", "--login", "-c",
                            "set -e; " +
                            "HOMEDIR=/home/" + user + "; " +
                            "mkdir -p $HOMEDIR/.ssh; " +
                            "chmod 700 $HOMEDIR/.ssh; " +
                            // Gateway private key (for ssh-gateway.sh to use)
                            "GW_KEY='" + gwKeyFile.replace(/\\/g, "/") + "'; " +
                            "if [ -f \"$GW_KEY\" ]; then " +
                            "cp \"$GW_KEY\" $HOMEDIR/.ssh/id_ed25519_gateway; " +
                            "chmod 600 $HOMEDIR/.ssh/id_ed25519_gateway; " +
                            "rm -f \"$GW_KEY\" \"${GW_KEY}.pub\"; " +
                            "fi; " +
                            // Access public key -> authorized_keys
                            "ACC_KEY='" + accKeyFile.replace(/\\/g, "/") + "'; " +
                            "if [ -f \"${ACC_KEY}.pub\" ]; then " +
                            "cat \"${ACC_KEY}.pub\" >> $HOMEDIR/.ssh/authorized_keys; " +
                            "chmod 600 $HOMEDIR/.ssh/authorized_keys; " +
                            "rm -f \"$ACC_KEY\" \"${ACC_KEY}.pub\"; " +
                            "fi"]);

    setupSillybearService();

    if (installer.value("gatewayHost") !== "") {
        setupGatewayService();
    }
}
